services:

  nltk:
    build:
      context: ./
      dockerfile: ./docker/nltk/Dockerfile
    container_name: nltk
    image: nltk
    volumes:
      - ./src:/nltk
      - ./nltk-data:/root/nltk-data
    ports:
      - "80:80"

networks:
  default:
    name: nltk_network
